apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "trickster.fullname" . }}
  labels:
    {{- include "trickster.labels" . | nindent 4 }}
rules:
- apiGroups:
  - trickstercache.org
  resources:
  - "*"
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - secrets
  verbs: ["get", "list", "watch"]
