apiVersion: v2
name: grafana-opscenter
description: Grafana Opscenter by AppsCode
type: application
version: v2023.03.23
appVersion: v2023.03.23
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
sources:
- https://github.com/open-viz
maintainers:
- name: appscode
  email: support@appscode.com
dependencies:
- name: grafana-ui-server
  repository: file://../grafana-ui-server
  condition: grafana-ui-server.enabled
  version: v0.0.2
- name: kube-grafana-dashboards
  repository: file://../kube-grafana-dashboards
  condition: kube-grafana-dashboards.enabled
  version: v2023.03.23
