project:
  name: Grafana Configurator by AppsCode
  shortName: Grafana Configurator
  url: https://github.com/open-viz/installer
  description: Grafana Configurator for ByteBuilders
  app: a Grafana Configurator
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: grafana-configurator
  values: "-- generate from values file --"
  valuesExample: "-- generate from values file --"
prerequisites:
- Kubernetes 1.16+
release:
  name: grafana-configurator
  namespace: kubeops
