{{- if .Values.serviceAccount.create -}}
apiVersion: v1
imagePullSecrets:
  - name: {{ include "thanos-querier.secretDockercfg" . }}
kind: ServiceAccount
metadata:
  name: {{ include "thanos-querier.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos-querier.labels" . | nindent 4 }}
  annotations:
    openshift.io/internal-registry-pull-secret-ref: {{ include "thanos-querier.secretDockercfg" . }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
secrets:
  - name: {{ include "thanos-querier.secretDockercfg" . }}
{{- end }}
