{{- if eq "prometheus.io/operator" ( include "monitoring.agent" . ) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "grafana-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.monitoring.serviceMonitor.labels }}
    {{- range $key, $val := .Values.monitoring.serviceMonitor.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
    {{- else }}
      {{- include "grafana-operator.selectorLabels" . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "grafana-operator.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: operator
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    scheme: https
    tlsConfig:
      ca:
        secret:
          name: {{ include "grafana-operator.fullname" . }}-apiserver-cert
          key: tls.crt
      serverName: "{{ include "grafana-operator.fullname" . }}.{{ .Release.Namespace }}.svc"
{{- end }}
