apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "grafana-ui-server.fullname" . }}
  labels:
    {{- include "grafana-ui-server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ui.openviz.dev
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - openviz.dev
  resources:
  - "*"
  verbs: ["get", "list", "watch"]
- apiGroups:
  - appcatalog.appscode.com
  resources:
  - "*"
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs: ["get", "list", "watch"]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs: ["get", "list", "watch"]
# permissions for prometheus syncer
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheuses
  verbs: ["get", "list", "watch"]
- apiGroups:
  - apps
  resources:
  - deployments
  verbs: ["get", "list", "watch"]
- apiGroups:
  - meta.k8s.appscode.com
  resources:
  - resourcequeries
  verbs: ["create"]
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups:
  - ""
  resources:
  - services/proxy
  verbs: ["*"]
- apiGroups:
  - charts.x-helm.dev
  resources:
  - clusterchartpresets
  - chartpresets
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups:
  - appcatalog.appscode.com
  resources:
  - appbindings
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# permissions for service monitor syncer
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - secrets
  verbs: ["get", "list", "watch", "create", "update", "patch"]
