apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring-operator.fullname" . }}-alertmanager-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring-operator.labels" . | nindent 4 }}
data:
  config.yaml: |
    receivers:
      - name: alertmanager-receiver
        {{- if .Values.alertmanager.email.enabled }}
        emailConfigs:
          - to: {{ .Values.alertmanager.email.to | quote }}
            from: {{ .Values.alertmanager.email.from | quote }}
            smarthost: {{ .Values.alertmanager.email.smarthost | quote }}
            authUsername: {{ .Values.alertmanager.email.authUsername | quote }}
            authPassword:
              name: {{ include "monitoring-operator.fullname" . }}-alertmanager-email
              key: password
            requireTLS: {{ .Values.alertmanager.email.requireTLS }}
            sendResolved: {{ .Values.alertmanager.email.sendResolved }}
            headers:
              - key: Subject
                value: >-
{{ .Files.Get "files/alertmanager/email.subject.tmpl" | indent 18 }}
            text: |
{{ .Files.Get "files/alertmanager/email.text.tmpl" | indent 14 }}
            html: |
{{ .Files.Get "files/alertmanager/email.html.tmpl" | indent 14 }}
        {{- end }}
        {{- if .Values.alertmanager.webhook.enabled }}
        webhookConfigs:
          - urlSecret:
              name: {{ include "monitoring-operator.fullname" . }}-alertmanager-webhook
              key: url
            sendResolved: {{ .Values.alertmanager.webhook.sendResolved }}
        {{- end }}
