{{- if and .Values.alertmanager.email.enabled .Values.alertmanager.email.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring-operator.fullname" . }}-alertmanager-email
  namespace: {{ .Release.Namespace }}
stringData:
  password: {{ .Values.alertmanager.email.password | quote }}
---
{{- end }}

{{- $webhook := .Values.alertmanager.webhook -}}
{{- $relay := $webhook.relay -}}
{{- $genericWebhookEnabled := and $webhook.enabled $webhook.url -}}
{{- $relayWebhookURLs := list -}}
{{- range $provider := list $relay.providers.googleChat $relay.providers.slack $relay.providers.msTeams $relay.providers.mattermost }}
  {{- if $provider.url }}
    {{- $relayWebhookURLs = append $relayWebhookURLs $provider.url -}}
  {{- end }}
{{- end }}
{{- $relayWebhookEnabled := and $webhook.enabled (gt (len $relayWebhookURLs) 0) -}}
{{- if or $genericWebhookEnabled $relayWebhookEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring-operator.fullname" . }}-alertmanager-webhook
  namespace: {{ .Release.Namespace }}
stringData:
  {{- if $genericWebhookEnabled }}
  url: {{ $webhook.url | quote }}
  {{- end }}
  {{- if $relayWebhookEnabled }}
  relay-url: {{ printf "http://%s.%s.svc:%v/v1/ingest/webhook" (include "monitoring-operator.alertmanagerWebhookRelayName" .) .Release.Namespace $relay.port | quote }}
  {{- end }}
{{- end }}

{{- if and $webhook.enabled (gt (len $relayWebhookURLs) 0) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring-operator.alertmanagerWebhookRelaySecretName" . }}
  namespace: {{ .Release.Namespace }}
stringData:
  urls: |-
{{- range $relayWebhookURLs }}
    {{ . }}
{{- end }}
{{- end }}
