{{- if and .Values.alertmanager.email.enabled .Values.alertmanager.email.secret.name .Values.alertmanager.email.secret.key .Values.alertmanager.email.secret.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.alertmanager.email.secret.name }}
  namespace: {{ .Release.Namespace }}
stringData:
  {{ .Values.alertmanager.email.secret.key }}: {{ .Values.alertmanager.email.secret.password | quote }}
---
{{- end }}

{{- if and .Values.alertmanager.webhook.enabled .Values.alertmanager.webhook.secret.name .Values.alertmanager.webhook.secret.key .Values.alertmanager.webhook.secret.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.alertmanager.webhook.secret.name }}
  namespace: {{ .Release.Namespace }}
stringData:
  {{ .Values.alertmanager.webhook.secret.key }}: {{ .Values.alertmanager.webhook.secret.url | quote }}
{{- end }}
