{{- if and .Values.alertmanager.email.enabled .Values.alertmanager.email.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring-operator.fullname" . }}-alertmanager-email
  namespace: {{ .Release.Namespace }}
stringData:
  password: {{ .Values.alertmanager.email.password | quote }}
---
{{- end }}

{{- if and .Values.alertmanager.webhook.enabled .Values.alertmanager.webhook.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring-operator.fullname" . }}-alertmanager-webhook
  namespace: {{ .Release.Namespace }}
stringData:
  url: {{ .Values.alertmanager.webhook.url | quote }}
{{- end }}
