apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "monitoring-operator.fullname" . }}
  labels:
    {{- include "monitoring-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["*"]
- apiGroups:
  - ui.openviz.dev
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - openviz.dev
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - appcatalog.appscode.com
  resources:
  - "*"
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - nodes
  verbs: ["get", "list", "watch"]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs: ["get", "list", "watch"]
# permissions for alertmanager config generator
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  verbs: ["get", "list", "watch"]
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagerconfigs
  verbs: ["get", "list", "watch", "create", "patch"]
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs: ["get", "list", "watch"]
# permissions for prometheus syncer
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheuses
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups:
  - apps
  resources:
  - deployments
  verbs: ["get", "list", "watch"]
- apiGroups:
  - meta.k8s.appscode.com
  resources:
  - resourcequeries
  verbs: ["create"]
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - rolebindings
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups:
  - ""
  resources:
  - services/proxy
  verbs: ["*"]
- apiGroups:
  - charts.x-helm.dev
  resources:
  - clusterchartpresets
  - chartpresets
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups:
  - appcatalog.appscode.com
  resources:
  - appbindings
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# permissions for service monitor syncer
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - secrets
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# permission to check ocm spoke
- apiGroups:
  - operator.open-cluster-management.io
  resources:
  - klusterlets
  verbs: ["get", "list", "watch"]
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - clusterclaims
  verbs: ["get", "list", "watch"]
