{{ $data := dict }}

{{- if .Values.platform.token }}
{{ $_ := set $data "token" .Values.platform.token }}
{{- end }}

{{- if .Values.platform.caBundle }}
{{ $_ := set $data "ca.crt" .Values.platform.caBundle }}
{{- end }}

{{- if $data }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring-operator.fullname" . }}-platform-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring-operator.labels" . | nindent 4 }}
type: Opaque
stringData: {{ $data | toJson }}

{{- end }}
