{{- if .Values.platform.caBundle }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring-operator.fullname" . }}-platform-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring-operator.labels" . | nindent 4 }}
stringData: {{ dict "tls.crt" .Values.platform.caBundle | toJson }}
{{- end }}
