{{- if .Values.rancher.baseURL }}

{{ $data := dict "baseURL" .Values.rancher.baseURL }}

{{ $_ := set $data "token" (required "rancher token is required" .Values.rancher.token) }}

{{- if .Values.rancher.caBundle }}
{{ $_ := set $data "ca.crt" .Values.rancher.caBundle }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring-operator.fullname" . }}-rancher-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring-operator.labels" . | nindent 4 }}
type: Opaque
stringData: {{ $data | toJson }}

{{- end }}
