{{- if .Values.rancher.baseURL }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring-operator.fullname" . }}-rancher-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  baseURL: {{ .Values.rancher.baseURL | quote }}
  token: {{ required "rancher token is required" .Values.rancher.token | quote }}

{{- end }}
