name: Release

on:
  push:
    tags:
      - "*.*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
          sudo mv bin/hub /usr/local/bin

      - name: Clone charts repository
        env:
          GITHUB_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
        run: |
          cd $HOME
          git clone https://1gtm:${GITHUB_TOKEN}@github.com/appscode/charts.git
          cd charts
          git config user.name "1gtm"
          git config user.email "1gtm@appscode.com"

      - name: Package
        run: |
          echo "install helm 3"
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          echo "package charts"
          for chart in grafana-operator
          do
            helm package charts/${chart}
            mkdir -p $HOME/charts/stable/${chart}
            mv ${chart}-*.tgz $HOME/charts/stable/${chart}
          done

      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
        run: |
          export PR_BRANCH=${GITHUB_REPOSITORY}/${GITHUB_RUN_ID}
          echo $PR_BRANCH
          cd $HOME/charts
          git checkout -b $PR_BRANCH
          git add --all
          git commit -a -s -m "Push Searchlight charts for $GITHUB_REF"
          git push origin $PR_BRANCH -f
          hub pull-request \
              --labels automerge \
              --message "Push Searchlight charts for $GITHUB_REF" \
              --message "Signed-off-by: $(git config --get user.name) <$(git config --get user.email)>" || true
